### ISSUE TITLE
hello,thank you your job,but it still no run

### ISSUE THREAD

**Issue by ulrictan** [hsnotebook/orabbix4zabbix4#1]
你好，我使用zabbix4.0，用这个orabbix插件，仍然是无法取到数据。
还是原来那个错误。
我把run.sh的sed配置都取消了。
在config.progs 我修改好我数据库配置，可是接收到的数据都是空值。和没有修改前的错误一样。不过就是修改前是接收到一大串乱字符，可是修改后就是空值。

**Comment by hsnotebook** [comment]
@ulrictan 需要执行一下, build.sh.

orabbix 目录下的 jar 包, 还是之前的, 需要编译下 src 目录中的 Sender.java, 并替换到 orabbix 下的 jar 包中, build.sh 会做这些工作.

**Comment by ulrictan** [comment]
重新编译后，运行有错误。我用的jdk8，ubuntu 16 zabbix4 
---------
Exception in thread "pool-1-thread-2" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: java/lang/invoke/StringConcatFactory
        at com.smartmarmot.orabbix.Sender.<init>(Sender.java:91)
        at com.smartmarmot.common.db.DBJob.run(DBJob.java:121)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: java/lang/invoke/StringConcatFactory
        ... 5 more
Caused by: java.lang.ClassNotFoundException: java.lang.invoke.StringConcatFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more
----

**Comment by hsnotebook** [comment]
@ulrictan 我本地试了下 (jdk8, ubuntu 18.04, zabbix 4), 修改好配置后, 直接 `sh run.sh`, 能够正常工作.

你可以先 `./build.sh` 后, 直接使用镜像, 看看还有问题么, 注意仓库先恢复 `git reset --hard HEAD`, 再执行 `./build.sh`.
